name: auth

services:
  keycloak: 
    image: quay.io/keycloak/keycloak:26.0.7
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://db-keycloak:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    depends_on:
      db-keycloak:
        condition: service_healthy
    networks:
      - tab-wise

  db-keycloak:
    image: mysql:8.0.41-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
    volumes:
      - ./.docker/keycloakdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
        - tab-wise

  auth-service:
    image: auth-service
    build: ./Authentication/
    ports: 
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./Authentication/:/source
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000"]  # Use dotnet watch for live reloading
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    restart: always
    networks:
      - tab-wise

networks:
  tab-wise:
    external: true
